### ISSUE TITLE
Is there any conditions for joinConversation or attributes for conversation?

### ISSUE THREAD

**Issue by MikasaAckerman** [twilio/twilio-conversations-demo-swift#7]
In my code，
user1 creates a conversation, and if use `conversation(withSidOrUniqueName:)`, user1 can join the conversation.
But if user2  uses `conversation(withSidOrUniqueName:)` directly, the error `DataFetchError.requiredDataCallsFailed`  comes back.
In the opposite , user2 creates a conversion but user1 can't join the conversation.
I'm sure there is correct channelId in backend and be used correctly in iOS...
So is there any conditions for joinConversation or attributes for conversation?
Thanks in advance.

**Comment by MikasaAckerman** [comment]
Solved this by setting user configuration with admin role.

**Comment by berkus** [comment]
Just making user an admin is a bad solution unless you fully understand the consequences.

In Conversations, each conversation is private, and as such it should **not** be visible to other users unless they are explicitly added to the conversation.

User1 can see the conversation because they are the creator, the only other user that can see it is the admin or REST backend. For user2 to see the same conversation either backend or user1 are supposed to add this user in the conversation.
